#pragma once

static const char DASHBOARD_HTML[] PROGMEM = R"HTML(<!doctype html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Indoor Sky</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#080a0d;color:#dce6ee;font:12px monospace}header{position:sticky;top:0;z-index:2;background:#080a0dee;border-bottom:1px solid #26313a;padding:12px 18px;display:flex;justify-content:space-between;gap:16px}h1{margin:0;color:#adf;font-size:16px;letter-spacing:.12em}.live,.healthy{color:#55ee88!important}.low{color:#ffcc66!important}.loss,.err{color:#ff6677!important}main{display:grid;grid-template-columns:repeat(auto-fit,minmax(360px,1fr));gap:12px;padding:12px}.scope{border:1px solid #202a32;background:#0c1015;min-width:0}.scope-head{padding:9px 11px;display:flex;justify-content:space-between;border-bottom:1px solid #202a32}.name{color:#8ba0af;text-transform:uppercase;letter-spacing:.1em}.reading{font-size:14px;color:white}canvas{display:block;width:100%;height:170px;background:#07090c}#diag{grid-column:1/-1;padding:12px;display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:8px;border:1px solid #202a32;background:#0c1015}.metric{color:#778894}.metric span{color:#dce6ee}.sub{color:#53616b;font-size:10px}.controls{display:flex;align-items:center;gap:8px;color:#8ba0af}.controls input{width:150px}.controls button{background:#17212a;color:#adf;border:1px solid #33424e;padding:4px 7px;font:11px monospace}
</style></head><body>
<header><h1>INDOOR SKY · SIGNALS</h1><div class="controls"><label>Presentation delay <input id="delay" type="range" min=".5" max="10" step=".25" value="6"><span id="delayValue">6.00s</span></label><button id="useRecommended">use recommended</button><div id="connection">connecting</div></div></header>
<main>
<section class="scope"><div class="scope-head"><span class="name">Temperature</span><span class="reading" id="tempValue">—</span></div><canvas id="temp"></canvas></section>
<section class="scope"><div class="scope-head"><span class="name">Humidity</span><span class="reading" id="humidityValue">—</span></div><canvas id="humidity"></canvas></section>
<section class="scope"><div class="scope-head"><span class="name">Pressure</span><span class="reading" id="pressureValue">—</span></div><canvas id="pressure"></canvas></section>
<section class="scope"><div class="scope-head"><span class="name">Microphone RMS</span><span class="reading" id="audioValue">—</span></div><canvas id="audio"></canvas></section>
<section id="diag">
<div class="metric">BME acquire <span id="bmeHz">—</span><div class="sub" id="bmeDetail"></div></div>
<div class="metric">Audio acquire <span id="audioHz">—</span><div class="sub" id="audioDetail"></div></div>
<div class="metric">Transport <span id="packetHz">—</span><div class="sub" id="transportDetail"></div></div>
<div class="metric">Network <span id="networkHealth">waiting</span><div class="sub" id="networkDetail"></div></div>
<div class="metric">Browser jitter <span id="jitter">—</span><div class="sub" id="browserDetail"></div></div>
<div class="metric">Buffer health <span id="bufferHealth">waiting</span><div class="sub" id="bufferDetail"></div></div>
</section></main><script>
class Ring{constructor(capacity,expectedUs){this.a=new Array(capacity);this.capacity=capacity;this.expectedUs=expectedUs;this.head=0;this.count=0;this.lastSeq=null;this.gaps=0;this.gapEvents=0;this.gapUs=0}push(s){if(this.lastSeq!==null&&s.seq!==this.lastSeq+1){const n=Math.max(0,s.seq-this.lastSeq-1);if(n){this.gaps+=n;this.gapEvents++;this.gapUs+=n*this.expectedUs}}this.lastSeq=s.seq;this.a[this.head]=s;this.head=(this.head+1)%this.capacity;this.count=Math.min(this.count+1,this.capacity)}latest(){return this.count?this.a[(this.head-1+this.capacity)%this.capacity]:null}visitRange(a,b,fn){const start=(this.head-this.count+this.capacity)%this.capacity;for(let i=0;i<this.count;i++){const s=this.a[(start+i)%this.capacity];if(s.t>=a&&s.t<=b)fn(s)}}}
const rings={temp:new Ring(2500,10000),humidity:new Ring(2500,10000),pressure:new Ring(2500,10000),audio:new Ring(6250,4000)};
let ws,packetLast=null,packetGaps=0,packetGapEvents=0,packetCount=0,lastArrival=0,intervalEma=50,jitterEma=0,bytesReceived=0,renderStalls=0,worstFrame=0,lastFrame=0,displayUnderruns=0,inUnderrun=false,underrunStarted=0,underrunMs=0,observationStarted=0,longestSilence=0,transportQueued=0,transportDropped=0,scheduledHz=20,firmwareUptimeMs=0,baselineDrops=null,baselineUptimeMs=0,networkRssi=0,wifiReconnects=0,oscFailures=0,oscSendAvgUs=0,oscSendMaxUs=0,oscSendStalls=0,viewEnd=null,presentationDelayUs=6000000,recommendedDelaySec=.5;
const WINDOW_US=10000000,connection=document.getElementById('connection'),delay=document.getElementById('delay'),delayValue=document.getElementById('delayValue');
delay.oninput=()=>{presentationDelayUs=+delay.value*1e6;delayValue.textContent=(+delay.value).toFixed(2)+'s';const n=newestTime();if(n)viewEnd=n-presentationDelayUs};useRecommended.onclick=()=>{delay.value=recommendedDelaySec;delay.oninput()};
const u64=(d,o)=>Number(d.getBigUint64(o,true));
function parsePacket(buffer){const d=new DataView(buffer);if(d.byteLength<76||String.fromCharCode(d.getUint8(0),d.getUint8(1),d.getUint8(2),d.getUint8(3))!=='INSK')return;const seq=d.getUint32(8,true);if(packetLast!==null&&seq!==packetLast+1){const n=Math.max(0,seq-packetLast-1);if(n){packetGaps+=n;packetGapEvents++}}packetLast=seq;packetCount++;bytesReceived+=d.byteLength;const now=performance.now();if(!observationStarted)observationStarted=now;if(lastArrival){const dt=now-lastArrival;if(dt>longestSilence)longestSilence=dt;intervalEma=intervalEma*.95+dt*.05;jitterEma=jitterEma*.9+Math.abs(dt-intervalEma)*.1}lastArrival=now;
bmeHz.textContent=(d.getUint16(32,true)/10).toFixed(1)+' Hz';audioHz.textContent=(d.getUint16(34,true)/10).toFixed(1)+' Hz';bmeDetail.textContent='queue '+d.getUint16(36,true)+' · overruns '+d.getUint32(24,true);audioDetail.textContent='queue '+d.getUint16(38,true)+' · overruns '+d.getUint32(28,true);transportQueued=d.getUint16(40,true);transportDropped=d.getUint32(44,true);scheduledHz=d.getUint16(48,true)/10;firmwareUptimeMs=d.getUint32(50,true);networkRssi=d.getInt16(54,true);wifiReconnects=d.getUint16(56,true);oscFailures=d.getUint32(60,true);oscSendAvgUs=d.getUint32(64,true);oscSendMaxUs=d.getUint32(68,true);oscSendStalls=d.getUint32(72,true);if(baselineDrops===null){baselineDrops=transportDropped;baselineUptimeMs=firmwareUptimeMs}
const nb=d.getUint16(20,true),na=d.getUint16(22,true);let o=d.getUint16(6,true);for(let i=0;i<nb;i++,o+=24){const s={seq:d.getUint32(o,true),t:u64(d,o+4)};rings.temp.push({...s,v:d.getFloat32(o+12,true)});rings.humidity.push({...s,v:d.getFloat32(o+16,true)});rings.pressure.push({...s,v:d.getFloat32(o+20,true)})}for(let i=0;i<na;i++,o+=16)rings.audio.push({seq:d.getUint32(o,true),t:u64(d,o+4),v:d.getFloat32(o+12,true)})}
function parseRouterBatch(message,bytes){if(message.type!=='sample_batch'||!Array.isArray(message.streams)||!message.streams.some(s=>s.name==='indoor-sky'))return;const seq=message.packetSequence;if(Number.isFinite(seq)){if(packetLast!==null&&seq!==packetLast+1){const n=Math.max(0,seq-packetLast-1);if(n){packetGaps+=n;packetGapEvents++}}packetLast=seq}packetCount++;bytesReceived+=bytes;const now=performance.now();if(!observationStarted)observationStarted=now;if(lastArrival){const dt=now-lastArrival;if(dt>longestSilence)longestSilence=dt;intervalEma=intervalEma*.95+dt*.05;jitterEma=jitterEma*.9+Math.abs(dt-intervalEma)*.1}lastArrival=now;const map={temperature:'temp',humidity:'humidity',pressure:'pressure',rms:'audio'};for(const stream of message.streams){if(stream.name!=='indoor-sky'||!map[stream.param])continue;for(const sample of stream.samples||[])rings[map[stream.param]].push({seq:sample[0],t:sample[1],v:sample[2]})}}
function connect(){ws=new WebSocket('wss://adrian-pi:3000');ws.onopen=()=>{connection.textContent='● router live';connection.className='live'};ws.onmessage=e=>{if(typeof e.data==='string'){try{parseRouterBatch(JSON.parse(e.data),e.data.length)}catch{}}};ws.onclose=()=>{connection.textContent='● router reconnecting';connection.className='err';setTimeout(connect,1000)};ws.onerror=()=>ws.close()}
async function pollStatus(){try{const s=await fetch('/status',{cache:'no-store'}).then(r=>r.json());bmeHz.textContent=s.bme_actual_hz.toFixed(1)+' Hz';audioHz.textContent=s.audio_actual_hz.toFixed(1)+' Hz';bmeDetail.textContent='overruns '+s.bme_overruns;audioDetail.textContent='overruns '+s.audio_overruns;transportQueued=0;transportDropped=s.transport_drops;scheduledHz=15.8;firmwareUptimeMs=s.uptime_ms;networkRssi=s.wifi_rssi_dbm;wifiReconnects=s.wifi_reconnects;oscFailures=s.osc_send_failures;oscSendAvgUs=s.osc_send_avg_us;oscSendMaxUs=s.osc_send_max_us;oscSendStalls=s.osc_send_stalls;if(baselineDrops===null){baselineDrops=transportDropped;baselineUptimeMs=firmwareUptimeMs}}catch{}setTimeout(pollStatus,1000)}
function newestTime(){let t=0;for(const r of Object.values(rings)){const s=r.latest();if(s&&s.t>t)t=s.t}return t}
function draw(name,color,unit,decimals,end){const canvas=document.getElementById(name),rect=canvas.getBoundingClientRect(),scale=devicePixelRatio||1,w=Math.max(1,Math.floor(rect.width*scale)),h=Math.max(1,Math.floor(rect.height*scale));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}const c=canvas.getContext('2d');c.clearRect(0,0,w,h);const ring=rings[name];if(!ring.latest()||end===null)return;const start=end-WINDOW_US,bins=Math.max(1,Math.ceil(w/2)),binUs=WINDOW_US/bins,first=Math.floor(start/binUs),count=bins+2,mins=new Float32Array(count),maxs=new Float32Array(count);mins.fill(Infinity);maxs.fill(-Infinity);let dataLo=Infinity,dataHi=-Infinity;ring.visitRange(start,end,s=>{dataLo=Math.min(dataLo,s.v);dataHi=Math.max(dataHi,s.v);const b=Math.floor(s.t/binUs)-first;if(b>=0&&b<count){mins[b]=Math.min(mins[b],s.v);maxs[b]=Math.max(maxs[b],s.v)}});if(dataLo===Infinity)return;let range=Math.max(1e-9,dataHi-dataLo),wantedLo=dataLo-range*.12,wantedHi=dataHi+range*.12;if(canvas._lo===undefined){canvas._lo=wantedLo;canvas._hi=wantedHi}else{canvas._lo=Math.min(canvas._lo,wantedLo);canvas._hi=Math.max(canvas._hi,wantedHi)}const lo=canvas._lo,hi=canvas._hi;c.strokeStyle='#1b252d';c.lineWidth=scale;c.beginPath();for(let i=1;i<4;i++){const y=h*i/4;c.moveTo(0,y);c.lineTo(w,y)}c.stroke();c.strokeStyle=color;c.lineWidth=2*scale;c.beginPath();let prev=-2;for(let b=0;b<count;b++){if(mins[b]===Infinity)continue;const x=(((first+b+.5)*binUs)-start)/WINDOW_US*w,y1=h-(mins[b]-lo)/(hi-lo)*h,y2=h-(maxs[b]-lo)/(hi-lo)*h;if(b!==prev+1)c.moveTo(x,y1);else c.lineTo(x,y1);if(y2!==y1)c.lineTo(x,y2);prev=b}c.stroke();c.fillStyle='#738592';c.font=10*scale+'px monospace';c.textBaseline='top';c.fillText('max '+dataHi.toFixed(decimals),5*scale,4*scale);c.textAlign='right';c.fillText('time window 10s',w-5*scale,4*scale);c.textBaseline='bottom';c.textAlign='left';c.fillText('min '+dataLo.toFixed(decimals),5*scale,h-4*scale);c.textAlign='right';c.fillText('peak-to-peak range '+(dataHi-dataLo).toFixed(decimals),w-5*scale,h-4*scale);c.textAlign='left';document.getElementById(name+'Value').textContent=ring.latest().v.toFixed(decimals)+' '+unit}
let lastPaint=0;function render(now){const newest=newestTime(),dt=lastFrame?now-lastFrame:0;if(lastFrame){if(dt>40)renderStalls++;worstFrame=Math.max(worstFrame,dt)}if(viewEnd===null&&newest)viewEnd=newest-presentationDelayUs;else if(lastFrame&&viewEnd!==null)viewEnd+=dt*1000;const underrun=viewEnd!==null&&viewEnd>newest;if(underrun&&!inUnderrun){displayUnderruns++;underrunStarted=now}else if(!underrun&&inUnderrun){underrunMs+=now-underrunStarted;underrunStarted=0}inUnderrun=underrun;lastFrame=now;if(!lastPaint||now-lastPaint>=1000/60){lastPaint=now;draw('temp','#66ddff','°C',4,viewEnd);draw('humidity','#75ee99','%',4,viewEnd);draw('pressure','#dd99ff','hPa',4,viewEnd);draw('audio','#ff6688','dBFS',2,viewEnd)}requestAnimationFrame(render)}
let prevPackets=0,prevBytes=0,prevPacketGaps=0,prevOscFailures=0,prevOscStalls=0;setInterval(()=>{const now=performance.now(),dp=packetCount-prevPackets,db=bytesReceived-prevBytes,observed=Math.max(.001,(now-observationStarted)/1000),avg=packetCount/observed,silence=lastArrival?now-lastArrival:0,totalUnderrun=underrunMs+(inUnderrun?now-underrunStarted:0),dropDelta=baselineDrops===null?0:transportDropped-baselineDrops,dropSec=Math.max(.001,(firmwareUptimeMs-baselineUptimeMs)/1000),recentGaps=packetGaps-prevPacketGaps,recentFailures=oscFailures-prevOscFailures,recentStalls=oscSendStalls-prevOscStalls;prevPackets=packetCount;prevBytes=bytesReceived;prevPacketGaps=packetGaps;prevOscFailures=oscFailures;prevOscStalls=oscSendStalls;packetHz.textContent=dp+' pkt/s';transportDetail.textContent='scheduled '+scheduledHz.toFixed(1)+' · avg '+avg.toFixed(1)+' · '+(db/1024).toFixed(1)+' KiB/s · packet gaps '+packetGapEvents+'/'+packetGaps+' · queue '+transportQueued+' · dropped '+dropDelta+' ('+(dropDelta/(dropSec/60)).toFixed(1)+'/min)';const offline=silence>2000,congested=!offline&&(recentGaps||recentFailures||recentStalls||oscSendAvgUs>20000),degraded=!offline&&!congested&&(networkRssi<-70||oscSendAvgUs>5000);networkHealth.textContent=offline?'offline':congested?'congested':degraded?'degraded':'healthy';networkHealth.className=offline||congested?'loss':degraded?'low':'healthy';networkDetail.textContent='RSSI '+networkRssi+' dBm · OSC send avg/max '+(oscSendAvgUs/1000).toFixed(1)+'/'+(oscSendMaxUs/1000).toFixed(1)+'ms · recent gaps/failures/stalls '+recentGaps+'/'+recentFailures+'/'+recentStalls+' · totals '+packetGaps+'/'+oscFailures+'/'+oscSendStalls+' · Wi-Fi reconnects '+wifiReconnects;jitter.textContent=jitterEma.toFixed(1)+' ms';browserDetail.textContent='silence now/max '+silence.toFixed(0)+'/'+longestSilence.toFixed(0)+'ms · sample gaps B/A events '+rings.temp.gapEvents+'/'+rings.audio.gapEvents+' missing '+rings.temp.gaps+'/'+rings.audio.gaps+' · underruns '+displayUnderruns+' for '+(totalUnderrun/1000).toFixed(1)+'s · render stalls '+renderStalls+' · worst '+worstFrame.toFixed(0)+'ms';recommendedDelaySec=Math.min(10,Math.max(.5,Math.ceil((longestSilence+500)/250)*.25));const lead=viewEnd===null?0:(newestTime()-viewEnd)/1e6,loss=packetGaps>0||dropDelta>0,adequate=+delay.value>=recommendedDelaySec;if(loss){bufferHealth.textContent='loss detected';bufferHealth.className='loss'}else if(inUnderrun||!adequate){bufferHealth.textContent=inUnderrun?'underrun':'increase delay';bufferHealth.className='low'}else{bufferHealth.textContent='healthy';bufferHealth.className='healthy'}bufferDetail.textContent='buffered '+lead.toFixed(2)+'s · configured '+(+delay.value).toFixed(2)+'s · recommended '+recommendedDelaySec.toFixed(2)+'s from '+(longestSilence/1000).toFixed(2)+'s max silence'+(loss?' · permanent loss cannot be filled by latency':' · observed delays covered')},1000);
connect();pollStatus();requestAnimationFrame(render);
</script></body></html>)HTML";
